import os
from supabase import create_client, Client

SUPABASE_URL = "https://ohyvrohshkevfvniunrh.supabase.co"
SUPABASE_KEY = "sb_publishable_nxbaSK1W0eGbjuxxIns5Wg_PKzORskC"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

GOOGLE_MAPS_API_KEY = "AIzaSyBHOY868vy36nWq7NjLgzsmeE_OeyxZK2I"